Richmond dev
CityofToronto/bdit_traffic_dashboard pull request #47
Opened 2019-09-30 20:20 UTC by chmnata

## What this pull request accomplishes:
Get radioitems that looks change style when selected and other small style changes into heroku

`Screenshot of dashboard before`
![image](https://user-images.githubusercontent.com/46324452/65913289-99ba3a00-e39d-11e9-996b-db6c8f20f161.png)

`Screenshot of dashboard after`
![image](https://user-images.githubusercontent.com/46324452/65913341-b8203580-e39d-11e9-8ffc-6f377d894829.png)

## Issue(s) this solves:
- #46 
- #43 
- #42 
- #29 
- #35 
- #41 
- #40 

## What, in particular, needs to reviewed:
- css changes
- dbc structure
- addition of sql file

2019-10-02 19:01 UTC, radumas commented
are the tabs supposed to not take up the whole window?
![image](https://user-images.githubusercontent.com/10623872/66073662-8043fa00-e525-11e9-8e7d-331af60a1e72.png)

2019-10-02 21:02 UTC, radumas requested changes
Some questions inline. 
The only two that are really blocking merger into the live dashboard:
- [x] Should the fonts be Libre Franklin?
- [ ] Do I need to change anything in the heroku postgresql database?

There are other question/comments but they don't affect the appearance of the Dash, so could be dealt with later.

2019-10-02 21:02 UTC, radumas commented on assets/dashboard.css
> +h1 { font-size: 2.0rem; line-height: 1.2; letter-spacing: -.1rem; margin-top: 0.6rem; margin-bottom: 0.6rem; margin-left: 0.6rem; color: #FFFFFF; font-weight: bold; background-color: #165788;}
Why does H1 have a background-color?

2019-10-02 21:02 UTC, radumas commented on assets/dashboard.css
> +  font-family: Arial;
Is it possible to use "Libre Franklin" instead?

2019-10-02 21:02 UTC, radumas commented on sql/baseline_view.sql
> +                    WHEN (a.street = ANY (ARRAY['Bathurst'::text, 'Spadina'::text, 'University'::text])) AND a.direction = 'SB'::text THEN 'Front'::text
This kind of logic sequence is a bit of a code smell. I feel like the from-to intersections should be in a lookup table.

2019-10-02 21:02 UTC, radumas commented on app.py
> +                             day_type, period, to_char(lower(period_range::TIMERANGE), 'FMHH AM')||' to '||to_char(upper(period_range::TIMERANGE), 'FMHH AM') as period_range , tt
Nice

2019-10-02 21:02 UTC, radumas commented on app.py
> +WEEKS = pandasql.read_sql('''SELECT * FROM data_analysis.richmond_closure_weeks order by week_number desc
Does anything need to be changed in the data in the heroku postgresql database?

2019-10-02 21:02 UTC, radumas commented on app.py
> +FONT_FAMILY = 'Arial'
Libre Franklin?

2019-10-02 21:02 UTC, radumas commented on app.py
> +app = dash.Dash(__name__, meta_tags=metas, external_stylesheets=[dbc.themes.BOOTSTRAP])
Sweet!
Do you think there should be a write-up somewhere about how we switched these components to dbc?

2019-10-02 21:02 UTC, radumas commented on app.py
> +                             automargin=True), #Prevents axis title from overlapping axis
Important!

2019-10-02 21:02 UTC, radumas commented on app.py
> +                                width=12, style={'backgroundColor': "#165788"})
If this is set here, why is it also set in `dashboard.css`?

2019-10-02 21:02 UTC, radumas commented on app.py
> +                                    html.Span("Selected  ", style={'display':'inline-block', 'margin-left':"10px"}),
This should be labelled as the legend.
Maybe create it above and drop it in here as a variable?

2019-10-02 21:02 UTC, radumas commented on app.py
> +                Output(TIME_TITLE, 'children')],
Innovation!

2019-10-03 01:17 UTC, chmnata commented on assets/dashboard.css
> +  font-family: Arial;
or Franklin Gothic?

2019-10-03 01:22 UTC, chmnata commented on app.py
> +WEEKS = pandasql.read_sql('''SELECT * FROM data_analysis.richmond_closure_weeks order by week_number desc
Yes, `data_analysis.richmond_closure_week` and `data_analysis.richmond_closure_month` were changed. They are in [sql/month_week.sql](https://github.com/CityofToronto/bdit_traffic_dashboard/blob/richmond-dev/sql/month_week.sql).

2019-10-04 15:03 UTC, chmnata commented on app.py
> +WEEKS = pandasql.read_sql('''SELECT * FROM data_analysis.richmond_closure_weeks order by week_number desc
I also changed `data_analysis.richmond_dash_baseline`, in sql/baseline_view.sql

2019-10-07 18:46 UTC, radumas commented
Creating tables for weeks and months to port over to Heroku

```sql
SELECT * INTO data_analysis.richmond_closure_months_tbl
FROM data_analysis.richmond_closure_months
LIMIT 1;

SELECT * INTO data_analysis.richmond_closure_weeks_tbl
FROM data_analysis.richmond_closure_weeks
LIMIT 1;
```

Transferring the schema to heroku
```bash
pg_dump -d bigdata -h 10.160.12.47 -t 'data_analysis.richmond_closure_*_tbl' -F p -O --schema-only | psql $heroku_string
```

Change table names:
```sql
ALTER TABLE data_analysis.richmond_closure_weeks_tbl RENAME TO richmond_closure_weeks; ALTER TABLE data_analysis.richmond_closure_months_tbl RENAME TO richmond_closure_months;
```

Sync data

```bash
psql $heroku_rds -c "\COPY (SELECT month, month_number FROM data_analysis.richmond_closure_months) TO STDOUT;" | psql $heroku_string -c "TRUNCATE data_analysis.richmond_closure_months; COPY data_analysis.richmond_closure_months(month, month_number) FROM STDIN;"
psql $heroku_rds -c "\COPY (SELECT week, week_number FROM data_analysis.richmond_closure_weeks) TO STDOUT;" | psql $heroku_string -c "TRUNCATE data_analysis.richmond_closure_weeks; COPY data_analysis.richmond_closure_weeks(week, week_number) FROM STDIN;"
```

About to include DAG

2019-10-07 18:54 UTC, radumas approved these changes

2019-10-07 18:54 UTC, radumas commented on sql/baseline_view.sql
> +         SELECT a.street, from_intersection, to_intersection, street_suffix,
Much cleaner

2019-10-07 18:55 UTC, merged